# Generated by Django 4.0.4 on 2022-07-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False, verbose_name='id marca')),
                ('nom_marca', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='id Región')),
                ('nombre_region', models.CharField(max_length=50, verbose_name='Nombre Región')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('idTipoEnvio', models.AutoField(primary_key=True, serialize=False, verbose_name='id envio')),
                ('tipoEnvio', models.CharField(max_length=50, verbose_name='tipo de envio')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Sucursal')),
                ('nombre_sucursal', models.CharField(max_length=100, verbose_name='Nombre Sucursal')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telefonos.region')),
            ],
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id_movil', models.AutoField(primary_key=True, serialize=False, verbose_name='id movil')),
                ('img', models.ImageField(upload_to='Telefonos/static/Telefonos/img/imgdjango', verbose_name='imagen')),
                ('costo', models.IntegerField(verbose_name='precio')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Celular')),
                ('cant', models.IntegerField(verbose_name='cantidad')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telefonos.marca')),
                ('tipo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telefonos.tipoenvio')),
            ],
        ),
    ]
