# Generated by Django 4.0.4 on 2022-05-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_marca')),
                ('nom_marca', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('idTipoEnvio', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_tipo_envio')),
                ('tipoEnvio', models.CharField(max_length=50, verbose_name='tipo_envio')),
            ],
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id_movil', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_movil')),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('costo', models.IntegerField(verbose_name='costo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telefonos.marca')),
                ('id_tipo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telefonos.tipoenvio')),
            ],
        ),
    ]
