# Generated by Django 4.0.4 on 2022-05-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movil',
            old_name='id_marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='movil',
            old_name='id_tipo_envio',
            new_name='tipo_envio',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='movil',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marca',
            name='id_marca',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id marca'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='costo',
            field=models.IntegerField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='id_movil',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id movil'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='img',
            field=models.ImageField(upload_to='Telefonos/static/Telefonos/img/imgdjango', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='tipoenvio',
            name='idTipoEnvio',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id envio'),
        ),
        migrations.AlterField(
            model_name='tipoenvio',
            name='tipoEnvio',
            field=models.CharField(max_length=50, verbose_name='tipo de envio'),
        ),
    ]
