# Generated by Django 4.0.4 on 2022-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='cant',
            field=models.IntegerField(default=10, verbose_name='cantidad'),
            preserve_default=False,
        ),
    ]
