# Generated by Django 4.0.4 on 2022-05-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0002_rename_id_marca_movil_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='id Región')),
                ('nombre_region', models.CharField(max_length=50, verbose_name='Nombre Región')),
            ],
        ),
        migrations.AlterField(
            model_name='movil',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Celular'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Sucursal')),
                ('img', models.ImageField(upload_to='Telefonos/static/Telefonos/img/imgdjango', verbose_name='Imagen')),
                ('nombre_sucursal', models.CharField(max_length=100, verbose_name='Nombre Sucursal')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telefonos.region')),
            ],
        ),
    ]
