# Generated by Django 4.0.4 on 2022-05-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0003_region_alter_movil_nombre_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='img',
        ),
    ]
