# Generated by Django 4.0.4 on 2022-07-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0003_alter_movil_cant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Boleta')),
                ('nom_cliente', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('estado', models.IntegerField(default=0, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
    ]
