# Generated by Django 4.0.4 on 2022-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0008_despacho_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='num_casa',
            field=models.IntegerField(default=450, verbose_name='Número de la casa/depa'),
        ),
    ]
