# Generated by Django 4.0.4 on 2022-07-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0009_despacho_num_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='num_boleta',
            field=models.ForeignKey(default=984418, on_delete=django.db.models.deletion.CASCADE, to='Telefonos.boleta'),
            preserve_default=False,
        ),
    ]
