# Generated by Django 4.0.4 on 2022-07-11 05:54

import Telefonos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telefonos', '0010_despacho_num_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fechaDespacho',
            field=models.DateTimeField(default=Telefonos.models.HoraDespacho, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fechaPreparacion',
            field=models.DateTimeField(default=Telefonos.models.HoraPreparacion, verbose_name='Fecha'),
        ),
    ]
